### ISSUE TITLE
[bug] User report from HAX daemon

### ISSUE THREAD

**Issue by Deb-G** [elmsln/issues#1953] opened 2024-03-19 17:04 UTC
Location: https://iam.hax.psu.edu/dlg131/sites/arth101/page-9/page
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1920x1080
Window size: 1710x1003
Battery: 100%
Connection: 4g
Bug you experienced: On the link above, I was unable to adjust the size of the image (make it larger or smaller).

![Screen Shot 2024-03-19 at 1 00 33 PM](https://github.com/elmsln/issues/assets/12716869/2dbed570-8b1f-4197-bc0a-b3285bc161f0)

**Comment by btopro** [comment] 2024-03-19 20:52
#1947 duplicate of this issue from last week

**Closed by btopro** 2024-03-19 20:52 UTC
